### ISSUE TITLE
Preview error

### ISSUE THREAD

**Issue by wujinhjun** [RIP21/react-simplemde-editor#206]
I used `electron: 20.0.3` & `react: 18.2.0` & `react-simplemde-editor:  5.0.2` & `easymde: 2.16.0`.
When preview content, find that content differences cannot occur.
Like this below:
![](https://raw.githubusercontent.com/wujinhjun/wujinhjun-pic/main/202209091355187.png)
![](https://raw.githubusercontent.com/wujinhjun/wujinhjun-pic/main/202209091355705.png)

Sorry to bother you. Thank you!

**Comment by phuhl** [comment]
Hey, had the same issue, for me it turned out, that the content is rendered correctly as HTML (e.g. h2 for ## heading) but there was no styling on it (in my case because tailwindcss stripped all styling off it).

Maybe that helps

**Comment by wujinhjun** [comment]
> Hey, had the same issue, for me it turned out, that the content is rendered correctly as HTML (e.g. h2 for ## heading) but there was no styling on it (in my case because tailwindcss stripped all styling off it).
> 
> Maybe that helps

Thank you. I find I reset the css by the [Reset CSS](https://meyerweb.com/eric/tools/css/reset/). Your suggestion is helpful!

**Comment by HOUSHENGREN** [comment]
easymde: 2.16.0.  can work!

**Comment by javayhu** [comment]
In my case, it's because Tailwindcss reset all styles, but I find a solution for this problem.

You can use [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography) for Markdown style, and you can set `prose` to [previewClass](https://github.com/Ionaru/easy-markdown-editor?tab=readme-ov-file#options-list) in SimpleMDE.Options.

boom, your preview is now working.

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/b48faae1-e05c-449c-a6a0-822773927ada">
