### ISSUE TITLE
can't use options when use getCodemirrorInstance to change state

### ISSUE THREAD

**Issue by kieuminhduc01** [RIP21/react-simplemde-editor#220]
pls help me @RIP21
This is my code: 

```js
export default function App() {
  const [cmInstance, setCmInstance] = useState<any>(null);
  const getCmInstanceCallback = useCallback((editor: any) => {
    setCmInstance(editor);
  }, []);

  useEffect(() => {
    if (!cmInstance) return;
    cmInstance.replaceSelection("output");
  }, [cmInstance]);

  return (
    <SimpleMDE options={{}} getCodemirrorInstance={getCmInstanceCallback} />
  );
}
```

I Got this error : "**_Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render._**"

**When I remove `option` property, It work fine**.

**Comment by RIP21** [comment]
Because on each state change you have a new js object created with a new reference that triggers a whole lot of machinery under the hood causing the editor to remount completely out from the DOM and back again with new options.
Yes, from your perspective nothing got changed, but from the perspective of the code and mechanism that shallow checks properties, it's a new object every single time.

Try moving options out of the App function body, or `useMemo` to memoize it.
