### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by lianel-artiles** [RIP21/react-simplemde-editor#221]
Just trying to render the basic implementation:
```js
import React, { useCallback, useState } from 'react'
import { SimpleMdeReact } from 'react-simplemde-editor'

function Input() {
  const [value, setValue] = useState('propValue')

  const onChange = useCallback((value) => {
    setValue(value)
  }, [])

  return <SimpleMdeReact value={value} onChange={onChange} />
}

export default Input
```
get this error on the codemirror lib

> ReferenceError: navigator is not defined
    at .../node_modules/codemirror/lib/codemirror.js:18:19

**Comment by RIP21** [comment]
It's probably because you're rendering that in Server Side Rendering env. So on the backend (I assume you're using Next or Remix or Astro). And obviously this is where window and navigator are absent. You need to make sure this component renders on the client side only. E.g. https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by r-4bb1t** [comment]
I am currently facing the same issue. Have you been able to resolve it?

**Comment by RIP21** [comment]
@r-4bb1t as mentioned above, it's because of SSR. You need to import this component dynamically so it never tries to run in SSR/node environment.
