### ISSUE TITLE
has fetching error with react query

### ISSUE THREAD

**Issue by ahmado-vic** [RIP21/react-simplemde-editor#234]
while i'm fetching post description for editing with react query it doesn't appear in editor but it works well with a normal fetch api

**Comment by RIP21** [comment]
I can't suggest anything without a reproduction or at least a code snippet.

**Comment by ahmado-vic** [comment]
here is my code.
//getSingleIssue function.
export const getSingleIssue = async (id: string) => {
  const response: AxiosResponse<Issue> = await axios.get(
    `http://localhost:3000/api/issues/${id}`
  );

  return response.data;
};

//fetching with react query.
const { data: issue } = useQuery({
    queryFn: () => getSingleIssue(id),
    queryKey: ['issues', { id }],
  });
![Screen Shot 2023-12-14 at 2 27 32 PM](https://github.com/RIP21/react-simplemde-editor/assets/8178897/b7cc7ad0-817e-409c-a0ea-47873dbc2817)

**Comment by RIP21** [comment]
I don't quite understand what happening. But passing `{...field}` may not work as you expect it to be. With this component, I would recommend you be as explicit as possible about each prop you pass. Otherwise, it may behave weirdly. This editor is definitely not going to be straightforward to use with libraries like `formik` or `react-hooks-form`
