### ISSUE TITLE
Add support for or docs for autosaving capabilities

### ISSUE THREAD

**Issue by raymestalez** [RIP21/react-simplemde-editor#44]
Hi! I'm trying to enable autosave, but it doesn't work. As the form loads, I am setting it's value from the state, so it seems to clear all the text simplemde has saved.

Is there a workaround for this?

**Comment by RIP21** [comment]
@raymestalez never tried it myself. If you found any workaround how to make it work please let us know. Or contribute into the README. 
Thanks.
I will try to take a look at this someday to make it work.

**Comment by RIP21** [comment]
@raymestalez I don't know how autosave is works under the hood, but I think that you should implement it yourself to make it 100% working for you.

Otherwise, I think what you should try to do is to use option.
```
	autosave: {
		enabled: true,
		uniqueId: "MyUniqueID",
		delay: 1000,
	}
```
Then be sure that you have explicit id prop on your SimpleMDE, and then try not to setup value prop at initial render, and see how autocomplete will work when it's uncontrolled. I assume it uses localStorage.

**Comment by RIP21** [comment]
Okay. It actually uses localStorage.
For example when id is set to `demo`
Record in localStorage is `smde_demo`
What you can basically do is to set up autosave option making sure that `uniqueId` matches `id` prop
And then in componentWillMount or constructor, you can recover the data from `localStorage` like
```
this.state.value = localStorage.get(`smde_${id}`) || this.props.value
```
Or whatever, you got an idea.
Good luck :)

**Comment by RIP21** [comment]
@raymestalez Here is the example.
https://github.com/RIP21/react-simplemde-editor#autosaving-example
