### ISSUE TITLE
Got a alert from Github

### ISSUE THREAD

**Issue by jadeydi** [RIP21/react-simplemde-editor#80]
![image](https://user-images.githubusercontent.com/416989/50944255-a8d52100-14ca-11e9-88d3-038d62557adc.png)

https://github.com/godiscourse/godiscourse/network/alerts

**Comment by RIP21** [comment]
I also got this one. Link now is 404. Not sure whether it's valid now. Maybe newer version if simplemde was released. But I'll take a look no worries.

**Comment by jadeydi** [comment]
It's a private message, sorry

Here is the screenshot:

![image](https://user-images.githubusercontent.com/416989/51293900-ad11b900-1a4b-11e9-9449-88637f4a2b01.png)

**Comment by RIP21** [comment]
I'll suggest to write to the simple mde itself.

czw., 17 sty 2019, 04:33: HunterQ <notifications@github.com> napisał(a):

**Comment by RIP21** [comment]
@jadeydi so. Basically, I took a look at this, and this is about `simplemde` itself. Since `simplemde` itself wasn't updated for 3 to 4 years there is nothing I can do.
Please open an issue in `simplemde` repo. If there is another fork of `simplemde` that is actually supported etc, I'll be glad to use it instead. Let me know here in the issue thread.

I'll close it since it's not related to this concrete project.
