### ISSUE TITLE
How to get access to the HTML string ?

### ISSUE THREAD

**Issue by maitray16** [RIP21/react-simplemde-editor#87]
I am trying to store the HTML string and will be using it later for a different application, so I wanted to know how can I access the HTML string that might be generated while showing it in preview. 

Thanks

**Comment by RIP21** [comment]
Hmmm. You mean you put some markdown into an editor, then you click on preview and you want to copy the HTML code that will be generated in preview somehow?
I think you can use ref to access editor instance and obtain it somehow.
But I think you better should use some plain markdown compilers instead and not an editor itself.

Maybe something here may help you, but not sure.
[Editor preview behaviour override implementation in my blog](https://github.com/RIP21/next-ololos-blog/blob/master/pages/edit/Editor/Editor.js#L192)
[Post helper function that renders markdown to HTML](https://github.com/RIP21/next-ololos-blog/blob/master/pages/post/renderPost.js#L8)

**Comment by maitray16** [comment]
Thanks, I'll take a look at it. Basically what I am trying to do is if I have for example the following markdown - 
* Item1
* Item2
* Item3

I want to get its corresponding HTML - 
<ul>
  <li>Item1</li>
  <li>Item2</li>
  <li>Item3</li>
</ul>

Assuming that internally the markdown would have to be compiled to HTML for the preview tab.

**Comment by RIP21** [comment]
@maitray16 compilers that I use in the examples and many others (google for them) is a way better approach than trying to steal HTML from the preview HTML. 
At the end of the day, I assume, `simplemde` has some markdown parser inside that does the same thing. That maybe makes sense, to save some bytes, of the bundle (hence not bring two parsers to the project), but if that is the case I would rather ask the author of `easymde` to extract markdown parser to some module, so you can import its parser as a function and generate HTML that you are looking for. Otherwise, use one of the available markdown to HTML/JSX parsers.
I'm closing this since it's answered I think :)

**Comment by maitray16** [comment]
Update - The second link with helper function seems to be great. Closing the issue

**Comment by RIP21** [comment]
@maitray16 here we go. Actually, they DO use a separate dependency for markdown parsing and it's `marked`
Feel free to import it and use outside of the `easymde`
https://github.com/markedjs/marked
Do not bring additional dependency for no reason ;)

**Comment by maitray16** [comment]
@RIP21 Thanks a lot for the help and swift response. The helper function you posted seems to working fine for my use case, so will be using that rather than adding another dependency, but its cool to know easymde's - parsing lib.
