### ISSUE TITLE
import 'easymde/dist/easymde.min.css' accour window is not defined in ssr

### ISSUE THREAD

**Issue by chnliquan** [RIP21/react-simplemde-editor#89]
I use react ssr to introduce the css file into the component, and I get an error, `window is not defined` 
i install `react-simplemde-editor` and  `easymde` in my project, the webpack loader as follows, can you help me to solve this problem, thank you

```
{
        test: /\.jsx?$/,
        exclude: [
          node_modules
        ],
        loader: 'babel-loader',
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
 }
```

**Comment by RIP21** [comment]
I'm not sure how CSS can affect it at all. But if we're talking about the editor, I really recommend you not to render editor itself on the server since he is very heavy on `window` object hence these kinds of issues will likely appear and it's rather hard to make it fully SSR compatible.
So please use `dynamic imports` or something like https://github.com/kadirahq/react-no-ssr may help you. 
I recommend you to copy paste this code directly since the lib itself is improperly published hence argues with versions of React etc. https://github.com/kadirahq/react-no-ssr/blob/master/src/index.js
Or maybe this one. (will require a bit more hacking but more reliable I assume)
https://github.com/mui-org/material-ui/blob/674c523dffd0997f08154bc3c513e200823ee228/packages/material-ui/src/NoSsr/NoSsr.js

And I'm closing this one since I think this is all I can do in this case. But feel free to reopen anyone who feels that I can fix it somehow.

**Comment by fkotsian** [comment]
If you're using a non-Nextjs SSR, can confirm a standard `React.lazy` + Suspense dynamic import works. Check it out: https://reactjs.org/docs/code-splitting.html#reactlazy
